// Extracted directly from Project Zomboid Build 42.20 source scripts & decompiled Java
// Source files:
// - media/scripts/generated/items/weapon.txt
// - media/scripts/generated/items/clothing.txt
// - zombie/CombatManager.java
// - zombie/combat/CombatConfigKey.java
// - zombie/characters/IsoZombie.java
// - zombie/characters/IsoGameCharacter.java
// - zombie/inventory/types/HandWeapon.java
// - zombie/inventory/InventoryItem.java

const WEAPON_CATALOG = [
  {
    "id": "Axe",
    "name": "Fire Axe",
    "category": "Axe",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 0.8,
    "maxDamage": 2.0,
    "critChance": 20.0,
    "critMultiplier": 5.0,
    "condMax": 13,
    "condLowerChance": 35,
    "weight": 3.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.2,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 13,
    "headConditionLowerMultiplier": 1.5
  },
  {
    "id": "WoodAxe",
    "name": "Wood Axe",
    "category": "Axe",
    "twoHand": true,
    "swingAnim": "Heavy",
    "isRanged": false,
    "minDamage": 1.3,
    "maxDamage": 3.0,
    "critChance": 50.0,
    "critMultiplier": 12.0,
    "condMax": 15,
    "condLowerChance": 40,
    "weight": 3.0,
    "maxHitCount": 3,
    "minRange": 0.61,
    "maxRange": 1.35,
    "pushBackMod": 0.3,
    "knockdownMod": 3.0,
    "swingTime": 0.5,
    "enduranceMod": 3.0,
    "hasSharpness": true,
    "headCondition": 15,
    "headConditionLowerMultiplier": 1.5
  },
  {
    "id": "HandAxe",
    "name": "Hand Axe",
    "category": "Axe",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.7,
    "maxDamage": 1.5,
    "critChance": 15.0,
    "critMultiplier": 5.0,
    "condMax": 10,
    "condLowerChance": 15,
    "weight": 1.5,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.1,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 10,
    "headConditionLowerMultiplier": 1.5
  },
  {
    "id": "AxeStone",
    "name": "Stone Axe",
    "category": "Axe",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 0.5,
    "maxDamage": 1.5,
    "critChance": 15.0,
    "critMultiplier": 5.0,
    "condMax": 5,
    "condLowerChance": 5,
    "weight": 2.0,
    "maxHitCount": 3,
    "minRange": 0.61,
    "maxRange": 1.2,
    "pushBackMod": 0.3,
    "knockdownMod": 1.5,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 5,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Crowbar",
    "name": "Crowbar",
    "category": "Blunt",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 0.6,
    "maxDamage": 1.15,
    "critChance": 20.0,
    "critMultiplier": 2.5,
    "condMax": 15,
    "condLowerChance": 70,
    "weight": 2.0,
    "maxHitCount": 3,
    "minRange": 0.61,
    "maxRange": 1.25,
    "pushBackMod": 0.5,
    "knockdownMod": 0.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "BaseballBat",
    "name": "Baseball Bat",
    "category": "Blunt",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 0.8,
    "maxDamage": 1.1,
    "critChance": 40.0,
    "critMultiplier": 2.0,
    "condMax": 15,
    "condLowerChance": 20,
    "weight": 2.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.25,
    "pushBackMod": 0.5,
    "knockdownMod": 2.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "BaseballBat_Nails",
    "name": "Spiked Baseball Bat",
    "category": "Blunt",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 1.0,
    "maxDamage": 1.5,
    "critChance": 30.0,
    "critMultiplier": 5.0,
    "condMax": 15,
    "condLowerChance": 10,
    "weight": 2.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.28,
    "pushBackMod": 0.5,
    "knockdownMod": 2.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Sledgehammer",
    "name": "Sledgehammer",
    "category": "Blunt",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 2.0,
    "maxDamage": 3.0,
    "critChance": 20.0,
    "critMultiplier": 2.0,
    "condMax": 10,
    "condLowerChance": 40,
    "weight": 6.0,
    "maxHitCount": 3,
    "minRange": 0.7,
    "maxRange": 1.35,
    "pushBackMod": 1.0,
    "knockdownMod": 3.0,
    "swingTime": 4.0,
    "enduranceMod": 4.0,
    "alwaysKnockdown": true,
    "swingAnim": "Heavy",
    "hasSharpness": false,
    "headCondition": 10,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Shovel",
    "name": "Shovel",
    "category": "Blunt",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 0.8,
    "maxDamage": 1.9,
    "critChance": 40.0,
    "critMultiplier": 2.0,
    "condMax": 10,
    "condLowerChance": 10,
    "weight": 2.0,
    "maxHitCount": 3,
    "minRange": 0.61,
    "maxRange": 1.6,
    "pushBackMod": 0.5,
    "knockdownMod": 2.0,
    "swingTime": 2.1,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 10,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "LeadPipe",
    "name": "Lead Pipe",
    "category": "Blunt",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.7,
    "maxDamage": 1.2,
    "critChance": 30.0,
    "critMultiplier": 2.0,
    "condMax": 15,
    "condLowerChance": 20,
    "weight": 1.5,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.15,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Hammer",
    "name": "Hammer",
    "category": "SmallBlunt",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.5,
    "maxDamage": 1.0,
    "critChance": 20.0,
    "critMultiplier": 3.0,
    "condMax": 10,
    "condLowerChance": 30,
    "weight": 1.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 1.1,
    "pushBackMod": 0.5,
    "knockdownMod": 0.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 10,
    "headConditionLowerMultiplier": 2.0
  },
  {
    "id": "PipeWrench",
    "name": "Pipe Wrench",
    "category": "SmallBlunt",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.5,
    "maxDamage": 1.0,
    "critChance": 25.0,
    "critMultiplier": 2.0,
    "condMax": 10,
    "condLowerChance": 25,
    "weight": 1.5,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.1,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 4.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Nightstick",
    "name": "Nightstick",
    "category": "SmallBlunt",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.6,
    "maxDamage": 1.1,
    "critChance": 25.0,
    "critMultiplier": 2.0,
    "condMax": 15,
    "condLowerChance": 20,
    "weight": 1.5,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.2,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Pan",
    "name": "Frying Pan",
    "category": "SmallBlunt",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.3,
    "maxDamage": 0.5,
    "critChance": 30.0,
    "critMultiplier": 2.0,
    "condMax": 10,
    "condLowerChance": 12,
    "weight": 1.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 1.1,
    "pushBackMod": 0.5,
    "knockdownMod": 1.3,
    "swingTime": 3.0,
    "enduranceMod": 1.3,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Katana",
    "name": "Katana",
    "category": "LongBlade",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 8.0,
    "maxDamage": 8.0,
    "critChance": 35.0,
    "critMultiplier": 6.0,
    "condMax": 10,
    "condLowerChance": 15,
    "weight": 2.0,
    "maxHitCount": 3,
    "minRange": 0.61,
    "maxRange": 1.4,
    "pushBackMod": 0.5,
    "knockdownMod": 0.0,
    "swingTime": 3.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Machete",
    "name": "Machete",
    "category": "LongBlade",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 2.0,
    "maxDamage": 3.0,
    "critChance": 20.0,
    "critMultiplier": 5.0,
    "condMax": 13,
    "condLowerChance": 25,
    "weight": 2.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.23,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 4.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "HuntingKnife",
    "name": "Hunting Knife",
    "category": "SmallBlade",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.6,
    "maxDamage": 1.2,
    "critChance": 50.0,
    "critMultiplier": 3.0,
    "condMax": 10,
    "condLowerChance": 15,
    "weight": 1.0,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 0.9,
    "pushBackMod": 0.01,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "KitchenKnife",
    "name": "Kitchen Knife",
    "category": "SmallBlade",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.3,
    "maxDamage": 0.7,
    "critChance": 25.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 2,
    "weight": 0.7,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 0.9,
    "pushBackMod": 0.01,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "MeatCleaver",
    "name": "Meat Cleaver",
    "category": "Axe",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.4,
    "maxDamage": 0.8,
    "critChance": 15.0,
    "critMultiplier": 5.0,
    "condMax": 10,
    "condLowerChance": 15,
    "weight": 1.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 4.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Screwdriver",
    "name": "Screwdriver",
    "category": "SmallBlade",
    "twoHand": false,
    "isRanged": false,
    "minDamage": 0.3,
    "maxDamage": 0.7,
    "critChance": 10.0,
    "critMultiplier": 10.0,
    "condMax": 10,
    "condLowerChance": 6,
    "weight": 0.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 0.85,
    "pushBackMod": 0.01,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "SpearCrafted",
    "name": "Crafted Spear",
    "category": "Spear",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 1.0,
    "maxDamage": 1.4,
    "critChance": 20.0,
    "critMultiplier": 5.0,
    "condMax": 5,
    "condLowerChance": 2,
    "weight": 2.0,
    "maxHitCount": 2,
    "minRange": 0.98,
    "maxRange": 1.4,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "SpearCraftedFireHardened",
    "name": "Fire-Hardened Spear",
    "category": "Spear",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 1.0,
    "maxDamage": 1.5,
    "critChance": 30.0,
    "critMultiplier": 10.0,
    "condMax": 7,
    "condLowerChance": 4,
    "weight": 2.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 1.4,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "SpearHuntingKnife",
    "name": "Spear with Hunting Knife",
    "category": "Spear",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 1.2,
    "maxDamage": 1.7,
    "critChance": 20.0,
    "critMultiplier": 5.0,
    "condMax": 9,
    "condLowerChance": 8,
    "weight": 3.0,
    "maxHitCount": 2,
    "minRange": 0.98,
    "maxRange": 1.48,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 10,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "SpearKnife",
    "name": "Spear with Kitchen Knife",
    "category": "Spear",
    "twoHand": true,
    "isRanged": false,
    "minDamage": 1.0,
    "maxDamage": 1.6,
    "critChance": 20.0,
    "critMultiplier": 5.0,
    "condMax": 7,
    "condLowerChance": 4,
    "weight": 2.7,
    "maxHitCount": 2,
    "minRange": 0.98,
    "maxRange": 1.45,
    "pushBackMod": 0.3,
    "knockdownMod": 0.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": true,
    "headCondition": 10,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Shotgun",
    "name": "JS-2000 Shotgun",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "aimingPerkCritModifier": 10,
    "useEndurance": false,
    "minDamage": 1.5,
    "maxDamage": 2.2,
    "critChance": 70.0,
    "critMultiplier": 12.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 4.0,
    "maxHitCount": 9,
    "minRange": 0.61,
    "maxRange": 12.0,
    "pushBackMod": 0.8,
    "knockdownMod": 8.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "ShotgunSawnoff",
    "name": "Sawed-off Shotgun",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "minDamage": 1.3,
    "maxDamage": 2.0,
    "critChance": 50.0,
    "critMultiplier": 10.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 3.0,
    "maxHitCount": 9,
    "minRange": 0.61,
    "maxRange": 10.0,
    "pushBackMod": 0.9,
    "knockdownMod": 8.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "DoubleBarrelShotgun",
    "name": "Double Barrel Shotgun",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "minDamage": 1.5,
    "maxDamage": 2.2,
    "critChance": 70.0,
    "critMultiplier": 12.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 4.0,
    "maxHitCount": 9,
    "minRange": 0.67,
    "maxRange": 15.0,
    "pushBackMod": 0.8,
    "knockdownMod": 8.0,
    "swingTime": 2.0,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Pistol",
    "name": "M9 Pistol (9mm)",
    "category": "Firearm",
    "twoHand": false,
    "isRanged": true,
    "minDamage": 0.6,
    "maxDamage": 1.0,
    "critChance": 20.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 1.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 15.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Pistol2",
    "name": "M1911 Pistol (.45)",
    "category": "Firearm",
    "twoHand": false,
    "isRanged": true,
    "minDamage": 0.9,
    "maxDamage": 1.2,
    "critChance": 20.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 1.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 12.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "Revolver_Long",
    "name": "Magnum (.44)",
    "category": "Firearm",
    "twoHand": false,
    "isRanged": true,
    "minDamage": 1.0,
    "maxDamage": 1.6,
    "critChance": 20.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 2.0,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 18.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "HuntingRifle",
    "name": "MSR788 Rifle (.308)",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "minDamage": 1.2,
    "maxDamage": 2.0,
    "critChance": 30.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 4.0,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 40.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "AssaultRifle",
    "name": "M16 Rifle (5.56)",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "minDamage": 1.0,
    "maxDamage": 1.6,
    "critChance": 20.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 4.0,
    "maxHitCount": 2,
    "minRange": 0.61,
    "maxRange": 30.0,
    "pushBackMod": 0.3,
    "knockdownMod": 4.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  },
  {
    "id": "AssaultRifle2",
    "name": "M14 Rifle (.308)",
    "category": "Firearm",
    "twoHand": true,
    "isRanged": true,
    "minDamage": 1.2,
    "maxDamage": 2.0,
    "critChance": 30.0,
    "critMultiplier": 4.0,
    "condMax": 10,
    "condLowerChance": 200,
    "weight": 4.5,
    "maxHitCount": 1,
    "minRange": 0.61,
    "maxRange": 40.0,
    "pushBackMod": 0.3,
    "knockdownMod": 2.0,
    "swingTime": 0.5,
    "enduranceMod": 1.0,
    "hasSharpness": false,
    "headCondition": 0,
    "headConditionLowerMultiplier": 1.0
  }
];

const STOMP_DATA = [
  { id: "Stomp_Boots", name: "Foot Stomp (Boots/Heavy)", category: "Unarmed", twoHand: false, isRanged: false, minDamage: 0.7, maxDamage: 1.0, critChance: 35.0, critMultiplier: 2.0, condMax: 999, condLowerChance: 999, weight: 0.0, maxHitCount: 1, minRange: 0.0, maxRange: 0.8, pushBackMod: 1.0, knockdownMod: 0.0, swingTime: 1.0, enduranceMod: 2.0, hasSharpness: false, stompPower: 2.5 },
  { id: "Stomp_Sneakers", name: "Foot Stomp (Shoes/Sneakers)", category: "Unarmed", twoHand: false, isRanged: false, minDamage: 0.7, maxDamage: 1.0, critChance: 35.0, critMultiplier: 2.0, condMax: 999, condLowerChance: 999, weight: 0.0, maxHitCount: 1, minRange: 0.0, maxRange: 0.8, pushBackMod: 1.0, knockdownMod: 0.0, swingTime: 1.0, enduranceMod: 2.0, hasSharpness: false, stompPower: 2.1 },
  { id: "Stomp_Barefoot", name: "Foot Stomp (Barefoot)", category: "Unarmed", twoHand: false, isRanged: false, minDamage: 0.7, maxDamage: 1.0, critChance: 35.0, critMultiplier: 2.0, condMax: 999, condLowerChance: 999, weight: 0.0, maxHitCount: 1, minRange: 0.0, maxRange: 0.8, pushBackMod: 1.0, knockdownMod: 0.0, swingTime: 1.0, enduranceMod: 2.0, hasSharpness: false, stompPower: 0.5 }
];

const COMBAT_CONFIG_DEFAULTS = {
  BASE_WEAPON_DAMAGE_MULTIPLIER: 0.3,
  WEAPON_LEVEL_DAMAGE_MULTIPLIER_INCREMENT: 0.1,
  PLAYER_RECEIVED_DAMAGE_MULTIPLIER: 0.4,
  NON_PLAYER_RECEIVED_DAMAGE_MULTIPLIER: 1.5,
  HEAD_HIT_DAMAGE_SPLIT_MODIFIER: 3.0,
  LEG_HIT_DAMAGE_SPLIT_MODIFIER: 0.05,
  GLOBAL_MELEE_DAMAGE_REDUCTION_MULTIPLIER: 0.15,
  DAMAGE_PENALTY_ONE_HANDED_TWO_HANDED_WEAPON_MULTIPLIER: 0.5,
  ADDITIONAL_CRITICAL_HIT_CHANCE_DEFAULT: 5.0,
  ADDITIONAL_CRITICAL_HIT_CHANCE_FROM_BEHIND: 30.0,
  ENDURANCE_LOSS_BASE_SCALE: 0.28,
  ENDURANCE_LOSS_WEIGHT_MODIFIER: 0.3,
  ENDURANCE_LOSS_FINAL_MULTIPLIER: 0.04,
  FLOOR_DAMAGE_MIN_MULTIPLIER: 5.0,
  FLOOR_DAMAGE_FLAT: false,
  ENDURANCE_LOSS_FLOOR_SHOVE_MULTIPLIER: 2.0,
  DURABILITY_WEAR_SCALE: 1.0
};

const ZOMBIE_TOUGHNESS_PRESETS = {
  1: { id: 1, name: "Tough", minHP: 3.5, maxHP: 3.8, meanHP: 3.65, critMod: -6.0 },
  2: { id: 2, name: "Normal", minHP: 1.8, maxHP: 2.1, meanHP: 1.95, critMod: 0.0 },
  3: { id: 3, name: "Fragile", minHP: 0.5, maxHP: 0.8, meanHP: 0.65, critMod: 6.0 },
  4: { id: 4, name: "Random", minHP: 0.5, maxHP: 3.8, meanHP: 2.15, critMod: 0.0 }
};


// TZonyne / La Resistenza — sandbox defaults from TierZonyne42 sandbox-options.txt
// Melee: min/max dmg, crit chance, crit multiplier are multiplied from SCRIPT BASE stats (OnWeaponSwing.lua).
// Ranged: damage is NOT scaled; aiming perk modifiers *= (dmgMod / tier) ^ rangedMulti.
// Stomp / BareHands: skipped. Sprinter% is per-zone (0-100); values <= 1% are treated as 0 (lrzombies_sand.lua).
const TZONYNE_DEFAULTS = {
  enabled: false,
  selectedTier: 1,
  night: false,
  rangedMulti: 1.0,
  sprinterHP: 0.1,
  shamblerHP: 2.0,
  nightSprinterFactor: 0.25,
  survivalHtk: 3,
  comfortHtk: 2,
  tiers: [
    { id: 1, name: "T1 Safe",  color: "#38bdf8", dmg: 1.00, critRate: 1.00, critMulti: 1.00, exp: 0, sprinterPct: 0,  lootRoll: 100 },
    { id: 2, name: "T2",       color: "#34d399", dmg: 0.85, critRate: 0.85, critMulti: 0.85, exp: 0, sprinterPct: 8,  lootRoll: 300 },
    { id: 3, name: "T3",       color: "#fbbf24", dmg: 0.60, critRate: 0.5, critMulti: 0.50, exp: 0, sprinterPct: 18, lootRoll: 500 },
    { id: 4, name: "T4",       color: "#f97316", dmg: 0.3, critRate: 0.3, critMulti: 0.1, exp: 0, sprinterPct: 32, lootRoll: 750 },
    { id: 5, name: "T5",       color: "#f43f5e", dmg: 0.2, critRate: 0.2, critMulti: 0.1, exp: 0, sprinterPct: 50, lootRoll: 1000 },
    { id: 6, name: "T6",       color: "#a855f7", dmg: 0.1, critRate: 0.1, critMulti: 0.1, exp: 0, sprinterPct: 72, lootRoll: 1000 }
  ]
};

function cloneTZonyne(src) {
  const s = src || TZONYNE_DEFAULTS;
  return {
    ...s,
    tiers: s.tiers.map(t => ({ ...t }))
  };
}

const PRESETS = {
  vanilla_apocalypse: {
    name: "Vanilla B42 (Standard Apocalypse)",
    description: "Impostazioni standard vanilla di Build 42. Multi-hit disabilitato, zombie normali (1.8 - 2.1 HP), scaling e durabilità originali.",
    sandbox: { toughness: 2, multiHit: false, customHP: null },
    config: { ...COMBAT_CONFIG_DEFAULTS }
  },
  vanilla_multihit: {
    name: "Vanilla B42 + Multi-Hit Attivo (Survivor)",
    description: "Impostazioni survivor/custom con Multi-Hit abilitato. Moltiplica radicalmente il power level abbattendo sciami con armi pesanti.",
    sandbox: { toughness: 2, multiHit: true, customHP: null },
    config: { ...COMBAT_CONFIG_DEFAULTS }
  },
  tough_zombies: {
    name: "Vanilla con Zombie Resistenti (Tough)",
    description: "Zombie con Toughness = Tough (3.5 - 3.8 HP). Raddoppia la vita dei non morti ma mantiene intatti i moltiplicatori di terra/testa.",
    sandbox: { toughness: 1, multiHit: false, customHP: null },
    config: { ...COMBAT_CONFIG_DEFAULTS }
  },
  rebalance_hardcore: {
    name: "Proposta Ribilanciamento: Gritty Survival",
    description: "Depotenzia i colpi a terra (da 5x a 2x), riduce il bonus testa da 3x a 1.5x, riduce la durabilità delle armi da 1x a 0.4x e aumenta l'HP zombie.",
    sandbox: { toughness: 1, multiHit: false, customHP: 4.0 },
    config: {
      ...COMBAT_CONFIG_DEFAULTS,
      HEAD_HIT_DAMAGE_SPLIT_MODIFIER: 1.6,
      FLOOR_DAMAGE_MIN_MULTIPLIER: 2.0,
      FLOOR_DAMAGE_FLAT: true,
      GLOBAL_MELEE_DAMAGE_REDUCTION_MULTIPLIER: 0.12,
      BASE_WEAPON_DAMAGE_MULTIPLIER: 0.25,
      WEAPON_LEVEL_DAMAGE_MULTIPLIER_INCREMENT: 0.05,
      DURABILITY_WEAR_SCALE: 2.5
    }
  },
  rebalance_endurance_focus: {
    name: "Proposta Ribilanciamento: Realismo & Attrito",
    description: "Mantiene il danno vanilla ma raddoppia l'usura e il consumo di fiato, e taglia i moltiplicatori testa/terra.",
    sandbox: { toughness: 2, multiHit: false, customHP: 2.5 },
    config: {
      ...COMBAT_CONFIG_DEFAULTS,
      FLOOR_DAMAGE_MIN_MULTIPLIER: 2.5,
      FLOOR_DAMAGE_FLAT: true,
      HEAD_HIT_DAMAGE_SPLIT_MODIFIER: 2.0,
      DURABILITY_WEAR_SCALE: 2.0,
      ENDURANCE_LOSS_FINAL_MULTIPLIER: 0.08
    }
  },
  la_resistenza: {
    name: "La Resistenza (TZonyne)",
    description: "Sandbox del server: moltiplicatori arma per tier zone, mix sprinter/shambler (HP 0.1 / 2.0), no multi-hit.",
    sandbox: { toughness: 1, multiHit: false, customHP: 2.0 },
    config: { ...COMBAT_CONFIG_DEFAULTS },
    tzonyne: { enabled: true, selectedTier: 1 }
  }
};